import type { NativePackageAuditRecord } from "../types";

export const NATIVE_INTERACTION_PACKAGE_AUDIT_RECORDS: NativePackageAuditRecord[] =
  [
    {
      packageName: "@elizaos/plugin-openai",
      role: "provider",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "1.6.0",
      alphaTagVersion: "2.0.0-alpha.537",
      compatibility: "alpha-only",
      note: "Official provider is only practical on alpha for the 2.x runtime line.",
    },
    {
      packageName: "@elizaos/plugin-anthropic",
      role: "provider",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "1.5.12",
      alphaTagVersion: "2.0.0-alpha.537",
      compatibility: "alpha-only",
      note: "Official provider is usable through alpha, not latest.",
    },
    {
      packageName: "@elizaos/plugin-pdf",
      role: "provider",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "2.0.0-alpha.11",
      alphaTagVersion: "2.0.0-alpha.537",
      compatibility: "alpha-only",
      note: "Official PDF plugin tracks the 2.x line through alpha.",
    },
    {
      packageName: "@elizaos/plugin-sql",
      role: "provider",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "1.7.2",
      alphaTagVersion: "2.0.0-alpha.20",
      compatibility: "alpha-only",
      note: "SQL stays on alpha to match the modern runtime path.",
    },
    {
      packageName: "@elizaos/plugin-telegram",
      role: "messaging",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "1.6.4",
      alphaTagVersion: "2.0.0-alpha.537",
      compatibility: "alpha-only",
      note: "Official Telegram plugin is still 1.x on latest, so alpha is the usable modern line.",
    },
    {
      packageName: "@elizaos/plugin-local-embedding",
      role: "knowledge",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "2.0.0-alpha.3",
      alphaTagVersion: "2.0.0-alpha.537",
      compatibility: "alpha-only",
      note: "Official local-embedding package is now owned directly on the alpha line.",
    },
    {
      packageName: "@elizaos/plugin-personality",
      role: "knowledge",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "2.0.0-alpha.1",
      alphaTagVersion: "2.0.0-alpha.9",
      compatibility: "alpha-only",
      note: "Official personality package is now owned directly on the alpha line.",
    },
    {
      packageName: "@elizaos/plugin-rolodex",
      role: "knowledge",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "2.0.0-alpha.3",
      alphaTagVersion: "2.0.0-alpha.10",
      compatibility: "alpha-only",
      note: "Official rolodex package is now owned directly on the alpha line.",
    },
    {
      packageName: "@elizaos/plugin-experience",
      role: "knowledge",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "2.0.0-alpha.1",
      alphaTagVersion: "2.0.0-alpha.11",
      compatibility: "alpha-only",
      note: "Official experience package is now owned directly on the alpha line.",
    },
  ];
